name = "uhpooh-backend"
type = "webpack"
account_id = ""  # Your Cloudflare account ID
workers_dev = true
compatibility_date = "2023-01-01"

[build]
command = "./mvnw clean package -DskipTests"
output_dir = "target"

[env.production]
routes = [
  { pattern = "api.*.[your-domain].com", zone_id = "[your-zone-id]" }
]

[build.upload]
format = "service-worker"
